a = input('Digite algo: ')
print('O tipo primitivo dese valor é', type(a))
print('Só tem espaços?',a.isspace())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maiuscula?', a.isupper())
print('Etsá em minuscula?', a.islower())
print('Está capitalizada?', a.istitle())
