# -*- coding: utf-8 -*-
"""Tratamento de Erros e exceções

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ht_COxBUYLVYIi-7NLtvT0QpHAGSD6sg
"""

try:
  a = int(input('Numerador: '))
  b = int(input('Denominador: '))
  r = a / b
except Exception as erro:
  print(f'Problema encontrado foi {erro.__class__}')
else:
  print(f'O resultado é {r}')
finally:
  print('Volte sempre, muito obrigado')

try:
  a = int(input('Numerador: '))
  b = int(input('Denominador: '))
  r = a / b
except (ValueError, TypeError):
  print('TIvemos um problema com os tipos de dados que vc digitou')
except ZeroDivisionError:
  print('Não é possivel dividir um numero por zero')
except KeyboardInterrupt:
  print('O usuario preferiu nãão informar os dados')
else:
  print(f'O resultado é {r:.1f}')
finally:
  print('Chegamos ao final do processo. Volte sempre')